---
title: "Hausaufgabe Session 3"
output: html_notebook
---

```{r}
library(tidyverse)
library(arules)
library(arulesViz)
```

```{r}
all <- read_csv("all.csv")
```

```{r}
i <- split(all$`Book-Author`,all$`User-ID`)
txn <- as(i, "transactions")
basket_rules <- apriori(txn, parameter = list(sup = 0.0015, conf = 0.08, minlen=2, target="rules"))
```

```{r}
myRules_Direct <- as(basket_rules, "data.frame")
basket_rules_hi <- head(basket_rules, by ="lift",100)
head(myRules_Direct, 20)
```
```{r}
plot(basket_rules_hi, method="graph", main="Author")
```

Die Namen der Autoren sind nicht immer gleich geschrieben, somit sind nicht alle Bewertungen eines Autoren berücksichtigt.

Beheben mit regulären Ausdrücken

```{r}
Author <- all %>%
  group_by(`Book-Author`) %>%
  summarise(AnzahlBücher = n()) %>%
  filter(AnzahlBücher > 15) %>%
  left_join(all)
```

```{r}
i_2 <- split(Author$`Book-Author`,Author$`User-ID`)
txn_2 <- as(i_2, "transactions")
basket_rules_2 <- apriori(txn_2, parameter = list(sup = 0.0015, conf = 0.08, minlen=2, target="rules"))
```

```{r}
myRules_Direct_2 <- as(basket_rules_2, "data.frame")
basket_rules_hi_2 <- head(basket_rules_2, by ="lift",100)
head(myRules_Direct_2, 20)
```

```{r}
plot(basket_rules_hi_2, method="graph", main="Author")
```

```{r}
Author_2 <- all %>%
  filter(`Book-Rating`>6) %>%
  group_by(`Book-Author`) %>%
  summarise(AnzahlBücher = n()) %>%
  filter(AnzahlBücher > 15) %>%
  left_join(all)
```


```{r}
i_3 <- split(Author_2$`Book-Author`,Author_2$`User-ID`)
txn_3 <- as(i_3, "transactions")
basket_rules_3 <- apriori(txn_3, parameter = list(sup = 0.0015, conf = 0.08, minlen=2, target="rules"))
```


```{r}
myRules_Direct_3 <- as(basket_rules_3, "data.frame")
basket_rules_hi_3 <- head(basket_rules_3, by ="lift",100)
head(myRules_Direct_3, 20)
```

```{r}
plot(basket_rules_hi_3, method="graph", main="Author")
```




